name: todo_app
description: To Do Application. Uygulama içerisinde kullanıcı kategori ve öncelik ekleyebilecek.
  Kategoriler içerisine yapılacak ekleyebilecek. yapılacaklar için hatırlatma ekleyebilecek



version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter



  cupertino_icons: ^0.1.3
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  provider: ^3.0.0+1
  font_awesome_flutter: ^8.8.1
  auto_size_text: ^2.1.0

  path_provider: ^1.6.5
  intl: ^0.16.1
  jiffy: ^3.0.1
  flutter_colorpicker: ^0.3.4
  flutter_local_notifications: ^1.4.2
  firebase_admob: any



dev_dependencies:
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.1

flutter:

  uses-material-design: true
  assets:
    - lang/en.json
    - lang/tr.json
    - lang/ar.json
    - lang/fr.json

